name: manage-azure-policy-377ff7d5
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Deny_firewall_rules_with_source_address_any/Internet_and_destination_port_any_but_not_80,_53,_443,_or_6516_0d735179-8f28-4b56-85ee-2537eca946ce/**'
#      - .github/workflows/manage-azure-policy-377ff7d5.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_377ff7d5}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Deny_firewall_rules_with_source_address_any/Internet_and_destination_port_any_but_not_80,_53,_443,_or_6516_0d735179-8f28-4b56-85ee-2537eca946ce/**
